### PR TITLE
Extract protobuf 23.4 formula

### PR DESCRIPTION
**Pull request by JoseHJBlanco**
Make protobuf version 23.4 available in our tap.

### CODE REVIEW

**Review by adamroyjones — COMMENTED** [review]
I'm a little surprised that so much is involved. protoc is (these days) statically linked, with binaries available for all targets, yet it looks as though it's recompiling it from source.

Do you have any idea why it's needing to do that? Or is this adapting something from an older version of protoc?

**Comment by JoseHJBlanco** [comment]
I don't know tbh. All of that was auto generated by this command:
```bash
brew extract --version=23 protobuf unravelin/tools
```

**Comment by adamroyjones** [comment]
Yes: it's identical to [this file](https://github.com/Homebrew/homebrew-core/blob/abc81e8b6f718659c322165f0d2ae87a3b4befb8/Formula/protobuf.rb).

I guess (using their tortured analogy) from the given "tap" (repository), the "bottle" (binary) from the "cellar" (registry) is something you can go ahead and download without recompilation—and Homebrew will only invoke a C++ compiler if you explicitly ask it to build the binary from source.

That makes sense to me. It does make me wonder if we'd have to mirror the "bottles" somehow lest everyone build everything from source, but it's not a big deal.

**Review by adamroyjones — APPROVED** [review]

**Comment by JoseHJBlanco** [comment]
Hmmm I see

**Pull request merged**
